import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/layout';
import requests from '../utils/requests';

export default function Home({ movies }) {

  // console.log(movies);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout movies={movies} />


    </div>
  )
}

export const getServerSideProps = async (ctx) => {


  const [
    popularData,
    trendingNow,
    topRated,
    actionMovies,
    comedyMovies,
    horrorMovies,
    romanceMovies,
    documentaries,
  ] = await Promise.all([
    await fetch(requests.fetchPopular).then((res) => res.json()),
    await fetch(requests.fetchTrending).then((res) => res.json())
  ]);

  return {
    props: {
      movies: {
        popular: popularData,
        trending: trendingNow
      }
    }
  }

}


// export async function getStaticProps() {

//   const res = await fetch(requests.fetchPopular);
//   const data = await res.json();

//   return {
//       props: {
//           popular: data
//       }
//   }

// }